[theme]
base="dark"
primaryColor="#5DADE2"
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"
font="sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[client]
toolbarMode = "minimal"

[ui]
hideTopBar = false
hideSidebarNav = false

[runner]
magicEnabled = true
fastReruns = true
